### ISSUE TITLE
libEGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lxgn** [MsLolita/grass#124]
python3 main.py
Traceback (most recent call last):
  File "/d01/scripts/grass2/mms/main.py", line 15, in <module>
    from core import Grass
  File "/d01/scripts/grass2/mms/core/__init__.py", line 1, in <module>
    from .grass import Grass
  File "/d01/scripts/grass2/mms/core/grass.py", line 17, in <module>
    from .grass_sdk.extension import GrassWs
  File "/d01/scripts/grass2/mms/core/grass_sdk/extension.py", line 11, in <module>
    from core.utils.exception import WebsocketClosedException, ProxyForbiddenException
  File "/d01/scripts/grass2/mms/core/utils/__init__.py", line 1, in <module>
    from .logger import logger
  File "/d01/scripts/grass2/mms/core/utils/logger.py", line 5, in <module>
    from PySide6.QtWidgets import QTextEdit
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
(venv) root@ub-grass-friends-5-182:/scripts/grass2/mms# cat /etc/issue
Ubuntu 24.04 LTS \n \l

(venv) root@ub-grass-friends-5-182:/scripts/grass2/mms# python3 -V
Python 3.12.3
(venv) root@ub-grass-friends-5-182:/scripts/grass2/mms#

**Comment by lxgn** [comment]
sudo apt install mesa-utils mesa-va-drivers mesa-vulkan-drivers
