### ISSUE TITLE
not work :(

### ISSUE THREAD

**Issue by Pon97** [MsLolita/grass#51]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from better_proxy import Proxy
  File "/usr/local/lib/python3.8/dist-packages/better_proxy/__init__.py", line 1, in <module>
    from .proxy import Proxy
  File "/usr/local/lib/python3.8/dist-packages/better_proxy/proxy.py", line 16, in <module>
    def _load_lines(filepath: Path | str) -> list[str]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by MsLolita** [comment]
upd to python 3.10 and upper

**Comment by Pon97** [comment]
thx. It's work :)
