### ISSUE TITLE
ValueError: too many file descriptors in select()

### ISSUE THREAD

**Issue by tamved** [MsLolita/grass#84]
Before curl add i have no problems with ~5000 accounts. 
after last update: start working well before about ~500 accounts. And stop with error:

how to solve it and why change to curl-ciffi?

Traceback (most recent call last):
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 671, in run_until_complete
    self.run_forever()
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 638, in run_forever
    self._run_once()
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1933, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many file descriptors in select()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\6\grassupdated\nodepart\main.py", line 176, in <module>
    asyncio.run(main())
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 193, in run
    with Runner(debug=debug, loop_factory=loop_factory) as runner:
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 62, in exit
    self.close()
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 70, in close
    _cancel_all_tasks(loop)
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 205, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 671, in run_until_complete
    self.run_forever()
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 638, in run_forever
    self._run_once()
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1933, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many file descriptors in select()

**Comment by akkawa** [comment]
I have the same problem

**Comment by Hamann1188** [comment]
its not script error
learn the features of the operating system

**Comment by rizexin** [comment]
same problame

**Comment by lilin998** [comment]
same problame

**Comment by donkeykongz** [comment]
open your website.py find headers['authorization'] = verify_token 

change to headers['Authorization'] = verify_token

**Comment by rizexin** [comment]
> open your website.py find headers['authorization'] = verify_token
> 
> change to headers['Authorization'] = verify_token

lol.. 

no change at all

**Comment by MsLolita** [comment]
upd script I remove curl-cffi
