### ISSUE TITLE
Curl errors

### ISSUE THREAD

**Issue by gaveer** [MsLolita/grass#85]
```
Login retrying... Failed to perform, curl: (35) BoringSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.getgrass.io:443 . See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Login retrying... Failed to perform, curl: (56) CONNECT tunnel failed, response 503. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

```

**Comment by gaveer** [comment]
```
95 | not handled exception | error: Failed to perform, curl: (35) BoringSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.getgrass.io:443 . See https://curl.se/libcurl/c/libcurl-errors.html first for more details. Traceback (most recent call last):
  File "C:\Users\xXx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\curl_cffi\requests\session.py", line 1333, in request
    await task
curl_cffi.curl.CurlError: Failed to perform, curl: (35) BoringSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.getgrass.io:443 . See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xXx\Desktop\grass-master\main.py", line 102, in worker_task
    await grass.start()
  File "C:\Users\xXx\Desktop\grass-master\core\grass.py", line 59, in start
    user_id = await self.enter_account()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xXx\Desktop\grass-master\core\grass_sdk\website.py", line 78, in enter_account
    res_json = await self.handle_login()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xXx\Desktop\grass-master\core\grass_sdk\website.py", line 156, in handle_login
    return await handler(self.login)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xXx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xXx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\xXx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\xXx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.240.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.240.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\xXx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xXx\Desktop\grass-master\core\grass_sdk\website.py", line 166, in login
    response = await self.session.post(url, headers=self.website_headers, data=json.dumps(json_data),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                       proxy=self.proxy)
                                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\xXx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\curl_cffi\requests\session.py", line 1338, in request
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.SSLError: Failed to perform, curl: (35) BoringSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.getgrass.io:443 . See https://curl.se/libcurl/c/libcurl-errors.html first for more details.```
